# Generated by Django 4.2.5 on 2023-09-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('mov_id', models.AutoField(primary_key=True, serialize=False)),
                ('mov_name', models.CharField(max_length=120)),
                ('mov_date', models.CharField(max_length=10)),
                ('mov_rat', models.DecimalField(decimal_places=1, max_digits=2)),
                ('mov_desc', models.TextField()),
                ('mov_dir', models.CharField(max_length=200)),
                ('mov_act', models.CharField(max_length=200)),
                ('mov_wir', models.CharField(max_length=200)),
                ('mov_tra', models.URLField()),
                ('mov_wat', models.URLField()),
                ('mov_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
