# Generated by Django 4.2.5 on 2023-09-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rev_mail',
            new_name='Mail_id',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rev_name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rev_con',
            new_name='Your_Review',
        ),
    ]
