# Generated by Django 4.2.5 on 2023-09-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_rename_rev_mail_review_mail_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='mov_img',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='mov_pro',
            field=models.URLField(default='https://assets.vogue.in/photos/5d7224d50ce95e0008696c55/2:3/w_2560%2Cc_limit/Joker.jpg'),
            preserve_default=False,
        ),
    ]
